// Helper: derive a stable, unique field key from a label
const k = (label) =>
  label
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "") || "field";

export const STARTER_SCHEMES = [
  {
    id: "builtin-dna-seq-run",
    name: "DNA Sequencing Run",
    description: "FASTQ/BAM files from sequencing instruments",
    isBuiltIn: true,
    forFormats: ["fastq", "fq", "fasta", "fa", "bam", "sam"],
    fields: [
      {
        id: "f-dsq-01",
        key: "sequencer_model",
        label: "Sequencer Model",
        type: "text",
        required: false,
        placeholder: "e.g. Oxford Nanopore MinION Mk1C",
        options: [],
        order: 0,
      },
      {
        id: "f-dsq-02",
        key: "flowcell_id",
        label: "Flow Cell ID",
        type: "text",
        required: false,
        placeholder: "",
        options: [],
        order: 1,
      },
      {
        id: "f-dsq-03",
        key: "library_prep_kit",
        label: "Library Prep Kit",
        type: "text",
        required: false,
        placeholder: "",
        options: [],
        order: 2,
      },
      {
        id: "f-dsq-04",
        key: "basecalling_software",
        label: "Basecalling Software",
        type: "text",
        required: false,
        placeholder: "e.g. Guppy 6.5.7",
        options: [],
        order: 3,
      },
      {
        id: "f-dsq-05",
        key: "phred_q30_percent",
        label: "Phred Q30 %",
        type: "number",
        required: false,
        placeholder: "",
        options: [],
        order: 4,
      },
      {
        id: "f-dsq-06",
        key: "total_reads",
        label: "Total Reads",
        type: "number",
        required: false,
        placeholder: "",
        options: [],
        order: 5,
      },
      {
        id: "f-dsq-07",
        key: "mean_read_length_bp",
        label: "Mean Read Length (bp)",
        type: "number",
        required: false,
        placeholder: "",
        options: [],
        order: 6,
      },
      {
        id: "f-dsq-08",
        key: "target_organism",
        label: "Target Organism",
        type: "text",
        required: false,
        placeholder: "",
        options: [],
        order: 7,
      },
      {
        id: "f-dsq-09",
        key: "run_date",
        label: "Run Date",
        type: "date",
        required: false,
        placeholder: "",
        options: [],
        order: 8,
      },
    ],
  },
  {
    id: "builtin-env-sample",
    name: "Environmental Sample",
    description: "eDNA, soil, water, air collection records",
    isBuiltIn: true,
    forFormats: ["fastq", "fq", "fasta", "fa", "csv"],
    fields: [
      {
        id: "f-env-01",
        key: "sample_type",
        label: "Sample Type",
        type: "select",
        required: true,
        placeholder: "",
        options: [
          "Soil",
          "Water",
          "Air",
          "Sediment",
          "Plant tissue",
          "Animal tissue",
          "Other",
        ],
        order: 0,
      },
      {
        id: "f-env-02",
        key: "habitat",
        label: "Habitat Description",
        type: "text",
        required: false,
        placeholder: "e.g. cloud forest edge",
        options: [],
        order: 1,
      },
      {
        id: "f-env-03",
        key: "substrate",
        label: "Substrate",
        type: "text",
        required: false,
        placeholder: "e.g. decaying hardwood",
        options: [],
        order: 2,
      },
      {
        id: "f-env-04",
        key: "depth_cm",
        label: "Depth (cm)",
        type: "number",
        required: false,
        placeholder: "",
        options: [],
        order: 3,
      },
      {
        id: "f-env-05",
        key: "ph",
        label: "pH",
        type: "number",
        required: false,
        placeholder: "",
        options: [],
        order: 4,
      },
      {
        id: "f-env-06",
        key: "temperature_c",
        label: "Temperature (°C)",
        type: "number",
        required: false,
        placeholder: "",
        options: [],
        order: 5,
      },
      {
        id: "f-env-07",
        key: "preservation_method",
        label: "Preservation Method",
        type: "text",
        required: false,
        placeholder: "e.g. Flash frozen",
        options: [],
        order: 6,
      },
      {
        id: "f-env-08",
        key: "dna_extraction_kit",
        label: "DNA Extraction Kit",
        type: "text",
        required: false,
        placeholder: "",
        options: [],
        order: 7,
      },
    ],
  },
  {
    id: "builtin-species-occurrence",
    name: "Species Occurrence",
    description: "iNaturalist-style field observation records",
    isBuiltIn: true,
    forFormats: ["csv", "json"],
    fields: [
      {
        id: "f-spo-01",
        key: "scientific_name",
        label: "Scientific Name",
        type: "text",
        required: true,
        placeholder: "",
        options: [],
        order: 0,
      },
      {
        id: "f-spo-02",
        key: "common_name",
        label: "Common Name",
        type: "text",
        required: false,
        placeholder: "",
        options: [],
        order: 1,
      },
      {
        id: "f-spo-03",
        key: "taxon_rank",
        label: "Taxon Rank",
        type: "select",
        required: false,
        placeholder: "",
        options: [
          "Species",
          "Subspecies",
          "Variety",
          "Genus",
          "Family",
          "Order",
          "Class",
          "Phylum",
          "Kingdom",
        ],
        order: 2,
      },
      {
        id: "f-spo-04",
        key: "kingdom",
        label: "Kingdom",
        type: "select",
        required: false,
        placeholder: "",
        options: [
          "Animalia",
          "Plantae",
          "Fungi",
          "Bacteria",
          "Archaea",
          "Protozoa",
          "Chromista",
          "Viruses",
        ],
        order: 3,
      },
      {
        id: "f-spo-05",
        key: "observation_type",
        label: "Observation Type",
        type: "select",
        required: false,
        placeholder: "",
        options: [
          "Visual",
          "Acoustic",
          "Physical specimen",
          "Photo",
          "Track/Sign",
          "Genetic",
        ],
        order: 4,
      },
      {
        id: "f-spo-06",
        key: "count",
        label: "Individual Count",
        type: "number",
        required: false,
        placeholder: "",
        options: [],
        order: 5,
      },
      {
        id: "f-spo-07",
        key: "life_stage",
        label: "Life Stage",
        type: "text",
        required: false,
        placeholder: "",
        options: [],
        order: 6,
      },
      {
        id: "f-spo-08",
        key: "reproductive_condition",
        label: "Reproductive Condition",
        type: "text",
        required: false,
        placeholder: "",
        options: [],
        order: 7,
      },
      {
        id: "f-spo-09",
        key: "identification_remarks",
        label: "ID Remarks",
        type: "textarea",
        required: false,
        placeholder: "",
        options: [],
        order: 8,
      },
    ],
  },
  {
    id: "builtin-darwin-core",
    name: "Darwin Core Occurrence",
    description: "Formal Darwin Core standard fields",
    isBuiltIn: true,
    forFormats: ["csv", "json", "zip"],
    fields: [
      {
        id: "f-dwc-01",
        key: "occurrenceid",
        label: "Occurrence ID",
        type: "text",
        required: false,
        placeholder: "",
        options: [],
        order: 0,
      },
      {
        id: "f-dwc-02",
        key: "basisofrecord",
        label: "Basis of Record",
        type: "select",
        required: false,
        placeholder: "",
        options: [
          "HumanObservation",
          "MachineObservation",
          "PreservedSpecimen",
          "LivingSpecimen",
          "MaterialSample",
          "FossilSpecimen",
        ],
        order: 1,
      },
      {
        id: "f-dwc-03",
        key: "scientificname",
        label: "Scientific Name",
        type: "text",
        required: true,
        placeholder: "",
        options: [],
        order: 2,
      },
      {
        id: "f-dwc-04",
        key: "kingdom",
        label: "Kingdom",
        type: "text",
        required: false,
        placeholder: "",
        options: [],
        order: 3,
      },
      {
        id: "f-dwc-05",
        key: "phylum",
        label: "Phylum",
        type: "text",
        required: false,
        placeholder: "",
        options: [],
        order: 4,
      },
      {
        id: "f-dwc-06",
        key: "class",
        label: "Class",
        type: "text",
        required: false,
        placeholder: "",
        options: [],
        order: 5,
      },
      {
        id: "f-dwc-07",
        key: "order",
        label: "Order",
        type: "text",
        required: false,
        placeholder: "",
        options: [],
        order: 6,
      },
      {
        id: "f-dwc-08",
        key: "family",
        label: "Family",
        type: "text",
        required: false,
        placeholder: "",
        options: [],
        order: 7,
      },
      {
        id: "f-dwc-09",
        key: "genus",
        label: "Genus",
        type: "text",
        required: false,
        placeholder: "",
        options: [],
        order: 8,
      },
      {
        id: "f-dwc-10",
        key: "eventdate",
        label: "Event Date",
        type: "date",
        required: false,
        placeholder: "",
        options: [],
        order: 9,
      },
      {
        id: "f-dwc-11",
        key: "country",
        label: "Country",
        type: "text",
        required: false,
        placeholder: "",
        options: [],
        order: 10,
      },
      {
        id: "f-dwc-12",
        key: "stateprovince",
        label: "State / Province",
        type: "text",
        required: false,
        placeholder: "",
        options: [],
        order: 11,
      },
      {
        id: "f-dwc-13",
        key: "locality",
        label: "Locality",
        type: "text",
        required: false,
        placeholder: "",
        options: [],
        order: 12,
      },
      {
        id: "f-dwc-14",
        key: "decimallatitude",
        label: "Decimal Latitude",
        type: "number",
        required: false,
        placeholder: "",
        options: [],
        order: 13,
      },
      {
        id: "f-dwc-15",
        key: "decimallongitude",
        label: "Decimal Longitude",
        type: "number",
        required: false,
        placeholder: "",
        options: [],
        order: 14,
      },
      {
        id: "f-dwc-16",
        key: "coorduncertainty",
        label: "Coord. Uncertainty (m)",
        type: "number",
        required: false,
        placeholder: "",
        options: [],
        order: 15,
      },
      {
        id: "f-dwc-17",
        key: "occurrencestatus",
        label: "Occurrence Status",
        type: "select",
        required: false,
        placeholder: "",
        options: ["present", "absent"],
        order: 16,
      },
    ],
  },
  {
    id: "builtin-soil",
    name: "Soil Physical/Chemical",
    description: "Abiotic soil measurement records",
    isBuiltIn: true,
    forFormats: ["csv", "txt"],
    fields: [
      {
        id: "f-sol-01",
        key: "soil_type",
        label: "Soil Type",
        type: "text",
        required: false,
        placeholder: "",
        options: [],
        order: 0,
      },
      {
        id: "f-sol-02",
        key: "horizon",
        label: "Soil Horizon",
        type: "text",
        required: false,
        placeholder: "e.g. A, B, C",
        options: [],
        order: 1,
      },
      {
        id: "f-sol-03",
        key: "bulk_density",
        label: "Bulk Density (g/cm³)",
        type: "number",
        required: false,
        placeholder: "",
        options: [],
        order: 2,
      },
      {
        id: "f-sol-04",
        key: "moisture_percent",
        label: "Moisture (%)",
        type: "number",
        required: false,
        placeholder: "",
        options: [],
        order: 3,
      },
      {
        id: "f-sol-05",
        key: "organic_carbon_percent",
        label: "Organic Carbon (%)",
        type: "number",
        required: false,
        placeholder: "",
        options: [],
        order: 4,
      },
      {
        id: "f-sol-06",
        key: "nitrogen_percent",
        label: "Total Nitrogen (%)",
        type: "number",
        required: false,
        placeholder: "",
        options: [],
        order: 5,
      },
      {
        id: "f-sol-07",
        key: "phosphorus_ppm",
        label: "Phosphorus (ppm)",
        type: "number",
        required: false,
        placeholder: "",
        options: [],
        order: 6,
      },
      {
        id: "f-sol-08",
        key: "cation_exchange",
        label: "Cation Exchange Cap.",
        type: "number",
        required: false,
        placeholder: "",
        options: [],
        order: 7,
      },
      {
        id: "f-sol-09",
        key: "texture_class",
        label: "Texture Class",
        type: "select",
        required: false,
        placeholder: "",
        options: [
          "Sand",
          "Loamy Sand",
          "Sandy Loam",
          "Loam",
          "Silt Loam",
          "Silt",
          "Sandy Clay Loam",
          "Clay Loam",
          "Silty Clay Loam",
          "Sandy Clay",
          "Silty Clay",
          "Clay",
        ],
        order: 8,
      },
    ],
  },
  {
    id: "builtin-pcr",
    name: "PCR / Amplification",
    description: "PCR setup and results tracking",
    isBuiltIn: true,
    forFormats: ["csv", "txt"],
    fields: [
      {
        id: "f-pcr-01",
        key: "target_gene",
        label: "Target Gene / Region",
        type: "text",
        required: true,
        placeholder: "e.g. 16S rRNA, ITS2, COI",
        options: [],
        order: 0,
      },
      {
        id: "f-pcr-02",
        key: "primer_forward",
        label: "Forward Primer",
        type: "text",
        required: false,
        placeholder: "",
        options: [],
        order: 1,
      },
      {
        id: "f-pcr-03",
        key: "primer_reverse",
        label: "Reverse Primer",
        type: "text",
        required: false,
        placeholder: "",
        options: [],
        order: 2,
      },
      {
        id: "f-pcr-04",
        key: "annealing_temp_c",
        label: "Annealing Temp (°C)",
        type: "number",
        required: false,
        placeholder: "",
        options: [],
        order: 3,
      },
      {
        id: "f-pcr-05",
        key: "cycle_count",
        label: "Cycle Count",
        type: "number",
        required: false,
        placeholder: "",
        options: [],
        order: 4,
      },
      {
        id: "f-pcr-06",
        key: "polymerase",
        label: "Polymerase",
        type: "text",
        required: false,
        placeholder: "",
        options: [],
        order: 5,
      },
      {
        id: "f-pcr-07",
        key: "band_size_bp",
        label: "Expected Band Size (bp)",
        type: "number",
        required: false,
        placeholder: "",
        options: [],
        order: 6,
      },
      {
        id: "f-pcr-08",
        key: "gel_result",
        label: "Gel Result",
        type: "select",
        required: false,
        placeholder: "",
        options: [
          "Positive",
          "Negative",
          "Faint band",
          "Contamination",
          "Not run",
        ],
        order: 7,
      },
      {
        id: "f-pcr-09",
        key: "remarks",
        label: "Remarks",
        type: "textarea",
        required: false,
        placeholder: "",
        options: [],
        order: 8,
      },
    ],
  },
  {
    id: "builtin-metagenomics",
    name: "Metagenomics Run",
    description: "QIIME2/BIOM-compatible metadata",
    isBuiltIn: true,
    forFormats: ["biom", "qza", "fastq", "fq"],
    fields: [
      {
        id: "f-meg-01",
        key: "pipeline",
        label: "Pipeline",
        type: "text",
        required: false,
        placeholder: "e.g. QIIME2 2023.9",
        options: [],
        order: 0,
      },
      {
        id: "f-meg-02",
        key: "target_region",
        label: "Target Region",
        type: "text",
        required: false,
        placeholder: "e.g. V3-V4, ITS1",
        options: [],
        order: 1,
      },
      {
        id: "f-meg-03",
        key: "primer_set",
        label: "Primer Set",
        type: "text",
        required: false,
        placeholder: "",
        options: [],
        order: 2,
      },
      {
        id: "f-meg-04",
        key: "asv_count",
        label: "ASV / OTU Count",
        type: "number",
        required: false,
        placeholder: "",
        options: [],
        order: 3,
      },
      {
        id: "f-meg-05",
        key: "read_count",
        label: "Read Count",
        type: "number",
        required: false,
        placeholder: "",
        options: [],
        order: 4,
      },
      {
        id: "f-meg-06",
        key: "rarefaction_depth",
        label: "Rarefaction Depth",
        type: "number",
        required: false,
        placeholder: "",
        options: [],
        order: 5,
      },
      {
        id: "f-meg-07",
        key: "classifier",
        label: "Classifier DB",
        type: "text",
        required: false,
        placeholder: "",
        options: [],
        order: 6,
      },
      {
        id: "f-meg-08",
        key: "min_freq_threshold",
        label: "Min Frequency Threshold",
        type: "number",
        required: false,
        placeholder: "",
        options: [],
        order: 7,
      },
    ],
  },
  {
    id: "builtin-microscopy",
    name: "Microscopy Session",
    description: "Light and electron microscopy records",
    isBuiltIn: true,
    forFormats: ["tif", "tiff", "png", "jpg", "cif"],
    fields: [
      {
        id: "f-mic-01",
        key: "microscope_type",
        label: "Microscope Type",
        type: "select",
        required: false,
        placeholder: "",
        options: [
          "Light/Brightfield",
          "Fluorescence",
          "Confocal",
          "SEM",
          "TEM",
          "Phase contrast",
          "DIC",
        ],
        order: 0,
      },
      {
        id: "f-mic-02",
        key: "magnification",
        label: "Magnification",
        type: "text",
        required: false,
        placeholder: "e.g. 40x, 100x oil",
        options: [],
        order: 1,
      },
      {
        id: "f-mic-03",
        key: "objective",
        label: "Objective",
        type: "text",
        required: false,
        placeholder: "",
        options: [],
        order: 2,
      },
      {
        id: "f-mic-04",
        key: "stain_protocol",
        label: "Stain / Protocol",
        type: "text",
        required: false,
        placeholder: "",
        options: [],
        order: 3,
      },
      {
        id: "f-mic-05",
        key: "fluorophore",
        label: "Fluorophore",
        type: "text",
        required: false,
        placeholder: "",
        options: [],
        order: 4,
      },
      {
        id: "f-mic-06",
        key: "excitation_nm",
        label: "Excitation (nm)",
        type: "number",
        required: false,
        placeholder: "",
        options: [],
        order: 5,
      },
      {
        id: "f-mic-07",
        key: "emission_nm",
        label: "Emission (nm)",
        type: "number",
        required: false,
        placeholder: "",
        options: [],
        order: 6,
      },
      {
        id: "f-mic-08",
        key: "image_remarks",
        label: "Image Remarks",
        type: "textarea",
        required: false,
        placeholder: "",
        options: [],
        order: 7,
      },
    ],
  },
  {
    id: "builtin-isa-tab",
    name: "ISA-Tab Study Record",
    description: "ISA-Tab compatible study / assay metadata",
    isBuiltIn: true,
    forFormats: ["txt", "tab"],
    fields: [
      {
        id: "f-isa-01",
        key: "study_title",
        label: "Study Title",
        type: "text",
        required: false,
        placeholder: "",
        options: [],
        order: 0,
      },
      {
        id: "f-isa-02",
        key: "study_identifier",
        label: "Study Identifier",
        type: "text",
        required: false,
        placeholder: "",
        options: [],
        order: 1,
      },
      {
        id: "f-isa-03",
        key: "assay_technology_type",
        label: "Assay Technology Type",
        type: "text",
        required: false,
        placeholder: "",
        options: [],
        order: 2,
      },
      {
        id: "f-isa-04",
        key: "measurement_type",
        label: "Measurement Type",
        type: "text",
        required: false,
        placeholder: "",
        options: [],
        order: 3,
      },
      {
        id: "f-isa-05",
        key: "technology_platform",
        label: "Technology Platform",
        type: "text",
        required: false,
        placeholder: "",
        options: [],
        order: 4,
      },
      {
        id: "f-isa-06",
        key: "protocol_ref",
        label: "Protocol Reference",
        type: "text",
        required: false,
        placeholder: "",
        options: [],
        order: 5,
      },
      {
        id: "f-isa-07",
        key: "factor_value",
        label: "Factor Value",
        type: "text",
        required: false,
        placeholder: "",
        options: [],
        order: 6,
      },
    ],
  },
  {
    id: "builtin-atmospheric",
    name: "Atmospheric Observation",
    description: "Weather station and atmospheric sensor logs",
    isBuiltIn: true,
    forFormats: ["csv", "txt", "json"],
    fields: [
      {
        id: "f-atm-01",
        key: "station_id",
        label: "Station ID",
        type: "text",
        required: false,
        placeholder: "",
        options: [],
        order: 0,
      },
      {
        id: "f-atm-02",
        key: "temperature_c",
        label: "Temperature (°C)",
        type: "number",
        required: false,
        placeholder: "",
        options: [],
        order: 1,
      },
      {
        id: "f-atm-03",
        key: "relative_humidity",
        label: "Relative Humidity (%)",
        type: "number",
        required: false,
        placeholder: "",
        options: [],
        order: 2,
      },
      {
        id: "f-atm-04",
        key: "pressure_hpa",
        label: "Pressure (hPa)",
        type: "number",
        required: false,
        placeholder: "",
        options: [],
        order: 3,
      },
      {
        id: "f-atm-05",
        key: "wind_speed_ms",
        label: "Wind Speed (m/s)",
        type: "number",
        required: false,
        placeholder: "",
        options: [],
        order: 4,
      },
      {
        id: "f-atm-06",
        key: "wind_direction_deg",
        label: "Wind Direction (°)",
        type: "number",
        required: false,
        placeholder: "",
        options: [],
        order: 5,
      },
      {
        id: "f-atm-07",
        key: "precipitation_mm",
        label: "Precipitation (mm)",
        type: "number",
        required: false,
        placeholder: "",
        options: [],
        order: 6,
      },
      {
        id: "f-atm-08",
        key: "sensor_model",
        label: "Sensor Model",
        type: "text",
        required: false,
        placeholder: "",
        options: [],
        order: 7,
      },
    ],
  },
  {
    id: "builtin-clinical-fhir",
    name: "Clinical Sample (FHIR)",
    description: "FHIR-adjacent patient sample records",
    isBuiltIn: true,
    forFormats: ["json", "xml"],
    fields: [
      {
        id: "f-fhi-01",
        key: "sample_id",
        label: "Sample ID",
        type: "text",
        required: false,
        placeholder: "",
        options: [],
        order: 0,
      },
      {
        id: "f-fhi-02",
        key: "specimen_type",
        label: "Specimen Type",
        type: "text",
        required: false,
        placeholder: "",
        options: [],
        order: 1,
      },
      {
        id: "f-fhi-03",
        key: "collection_date",
        label: "Collection Date",
        type: "date",
        required: false,
        placeholder: "",
        options: [],
        order: 2,
      },
      {
        id: "f-fhi-04",
        key: "body_site",
        label: "Body Site",
        type: "text",
        required: false,
        placeholder: "",
        options: [],
        order: 3,
      },
      {
        id: "f-fhi-05",
        key: "collection_method",
        label: "Collection Method",
        type: "text",
        required: false,
        placeholder: "",
        options: [],
        order: 4,
      },
      {
        id: "f-fhi-06",
        key: "storage_conditions",
        label: "Storage Conditions",
        type: "text",
        required: false,
        placeholder: "",
        options: [],
        order: 5,
      },
      {
        id: "f-fhi-07",
        key: "processing_method",
        label: "Processing Method",
        type: "text",
        required: false,
        placeholder: "",
        options: [],
        order: 6,
      },
      {
        id: "f-fhi-08",
        key: "clinical_remarks",
        label: "Clinical Remarks",
        type: "textarea",
        required: false,
        placeholder: "",
        options: [],
        order: 7,
      },
    ],
  },
  {
    id: "builtin-custom-blank",
    name: "Custom (Blank)",
    description: "Start entirely from scratch — no pre-defined fields",
    isBuiltIn: true,
    forFormats: ["*"],
    fields: [],
  },
];
