// Built-in starter schemes. isBuiltIn=true means duplicated before editing.
export const STARTER_SCHEMES = [
  {
    id: 'builtin-dna-seq-run',
    name: 'DNA Sequencing Run',
    description: 'FASTQ/BAM files from sequencing instruments',
    isBuiltIn: true,
    forFormats: ['fastq','fq','fasta','fa','bam','sam'],
    fields: [
      { id:'sequencer_model',       label:'Sequencer Model',         type:'text',     required:false, placeholder:'e.g. Oxford Nanopore MinION Mk1C' },
      { id:'flowcell_id',           label:'Flow Cell ID',            type:'text',     required:false },
      { id:'library_prep_kit',      label:'Library Prep Kit',        type:'text',     required:false },
      { id:'basecalling_software',  label:'Basecalling Software',    type:'text',     required:false, placeholder:'e.g. Guppy 6.5.7' },
      { id:'phred_q30_percent',     label:'Phred Q30 %',             type:'number',   required:false },
      { id:'total_reads',           label:'Total Reads',             type:'number',   required:false },
      { id:'mean_read_length',      label:'Mean Read Length (bp)',   type:'number',   required:false },
      { id:'target_organism',       label:'Target Organism',         type:'text',     required:false },
      { id:'run_date',              label:'Run Date',                type:'date',     required:false },
    ],
  },
  {
    id: 'builtin-env-sample',
    name: 'Environmental Sample',
    description: 'eDNA, soil, water, air collection records',
    isBuiltIn: true,
    forFormats: ['fastq','fq','fasta','fa','csv'],
    fields: [
      { id:'sample_type',           label:'Sample Type',             type:'select',   required:true,  options:['Soil','Water','Air','Sediment','Plant tissue','Animal tissue','Other'] },
      { id:'habitat',               label:'Habitat Description',     type:'text',     required:false },
      { id:'substrate',             label:'Substrate',               type:'text',     required:false },
      { id:'depth_cm',              label:'Depth (cm)',              type:'number',   required:false },
      { id:'ph',                    label:'pH',                      type:'number',   required:false },
      { id:'temperature_c',         label:'Temperature (°C)',        type:'number',   required:false },
      { id:'preservation_method',   label:'Preservation Method',     type:'text',     required:false, placeholder:'e.g. Flash frozen, RNAlater' },
      { id:'dna_extraction_kit',    label:'DNA Extraction Kit',      type:'text',     required:false },
    ],
  },
  {
    id: 'builtin-species-occurrence',
    name: 'Species Occurrence',
    description: 'iNaturalist-style field observation records',
    isBuiltIn: true,
    forFormats: ['csv','json'],
    fields: [
      { id:'scientific_name',       label:'Scientific Name',         type:'text',     required:true },
      { id:'common_name',           label:'Common Name',             type:'text',     required:false },
      { id:'taxon_rank',            label:'Taxon Rank',              type:'select',   required:false, options:['Species','Subspecies','Variety','Genus','Family','Order','Class','Phylum','Kingdom'] },
      { id:'kingdom',               label:'Kingdom',                 type:'select',   required:false, options:['Animalia','Plantae','Fungi','Bacteria','Archaea','Protozoa','Chromista','Viruses'] },
      { id:'observation_type',      label:'Observation Type',        type:'select',   required:false, options:['Visual','Acoustic','Physical specimen','Photo','Track/Sign','Genetic'] },
      { id:'count',                 label:'Individual Count',        type:'number',   required:false },
      { id:'life_stage',            label:'Life Stage',              type:'text',     required:false },
      { id:'reproductive_condition',label:'Reproductive Condition',  type:'text',     required:false },
      { id:'identification_remarks',label:'ID Remarks',              type:'textarea', required:false },
    ],
  },
  {
    id: 'builtin-darwin-core',
    name: 'Darwin Core Occurrence',
    description: 'Formal Darwin Core standard fields',
    isBuiltIn: true,
    forFormats: ['csv','json','zip'],
    fields: [
      { id:'occurrenceID',          label:'Occurrence ID',           type:'text',     required:false },
      { id:'basisOfRecord',         label:'Basis of Record',         type:'select',   required:false, options:['HumanObservation','MachineObservation','PreservedSpecimen','LivingSpecimen','MaterialSample','FossilSpecimen'] },
      { id:'scientificName',        label:'Scientific Name',         type:'text',     required:true },
      { id:'kingdom',               label:'Kingdom',                 type:'text',     required:false },
      { id:'phylum',                label:'Phylum',                  type:'text',     required:false },
      { id:'class',                 label:'Class',                   type:'text',     required:false },
      { id:'order',                 label:'Order',                   type:'text',     required:false },
      { id:'family',                label:'Family',                  type:'text',     required:false },
      { id:'genus',                 label:'Genus',                   type:'text',     required:false },
      { id:'eventDate',             label:'Event Date',              type:'date',     required:false },
      { id:'country',               label:'Country',                 type:'text',     required:false },
      { id:'stateProvince',         label:'State / Province',        type:'text',     required:false },
      { id:'locality',              label:'Locality',                type:'text',     required:false },
      { id:'decimalLatitude',       label:'Decimal Latitude',        type:'number',   required:false },
      { id:'decimalLongitude',      label:'Decimal Longitude',       type:'number',   required:false },
      { id:'coordinateUncertaintyInMeters', label:'Coord. Uncertainty (m)', type:'number', required:false },
      { id:'occurrenceStatus',      label:'Occurrence Status',       type:'select',   required:false, options:['present','absent'] },
    ],
  },
  {
    id: 'builtin-soil',
    name: 'Soil Physical/Chemical',
    description: 'Abiotic soil measurement records',
    isBuiltIn: true,
    forFormats: ['csv','txt'],
    fields: [
      { id:'soil_type',             label:'Soil Type',               type:'text',     required:false },
      { id:'horizon',               label:'Soil Horizon',            type:'text',     required:false, placeholder:'e.g. A, B, C' },
      { id:'bulk_density',          label:'Bulk Density (g/cm³)',    type:'number',   required:false },
      { id:'moisture_percent',      label:'Moisture (%)',            type:'number',   required:false },
      { id:'organic_carbon_percent',label:'Organic Carbon (%)',      type:'number',   required:false },
      { id:'nitrogen_percent',      label:'Total Nitrogen (%)',      type:'number',   required:false },
      { id:'phosphorus_ppm',        label:'Phosphorus (ppm)',        type:'number',   required:false },
      { id:'cation_exchange',       label:'Cation Exchange Cap.',    type:'number',   required:false },
      { id:'texture_class',         label:'Texture Class',           type:'select',   required:false, options:['Sand','Loamy Sand','Sandy Loam','Loam','Silt Loam','Silt','Sandy Clay Loam','Clay Loam','Silty Clay Loam','Sandy Clay','Silty Clay','Clay'] },
    ],
  },
  {
    id: 'builtin-pcr',
    name: 'PCR / Amplification',
    description: 'PCR setup and results tracking',
    isBuiltIn: true,
    forFormats: ['csv','txt'],
    fields: [
      { id:'target_gene',           label:'Target Gene / Region',    type:'text',     required:true,  placeholder:'e.g. 16S rRNA, ITS2, COI' },
      { id:'primer_forward',        label:'Forward Primer',          type:'text',     required:false },
      { id:'primer_reverse',        label:'Reverse Primer',          type:'text',     required:false },
      { id:'annealing_temp_c',      label:'Annealing Temp (°C)',     type:'number',   required:false },
      { id:'cycle_count',           label:'Cycle Count',             type:'number',   required:false },
      { id:'polymerase',            label:'Polymerase',              type:'text',     required:false },
      { id:'band_size_bp',          label:'Expected Band Size (bp)', type:'number',   required:false },
      { id:'gel_result',            label:'Gel Result',              type:'select',   required:false, options:['Positive','Negative','Faint band','Contamination','Not run'] },
      { id:'remarks',               label:'Remarks',                 type:'textarea', required:false },
    ],
  },
  {
    id: 'builtin-metagenomics',
    name: 'Metagenomics Run',
    description: 'QIIME2/BIOM-compatible metadata',
    isBuiltIn: true,
    forFormats: ['biom','qza','fastq','fq'],
    fields: [
      { id:'pipeline',              label:'Pipeline',                type:'text',     required:false, placeholder:'e.g. QIIME2 2023.9, mothur 1.48' },
      { id:'target_region',         label:'Target Region',           type:'text',     required:false, placeholder:'e.g. V3-V4, ITS1' },
      { id:'primer_set',            label:'Primer Set',              type:'text',     required:false },
      { id:'asv_count',             label:'ASV / OTU Count',         type:'number',   required:false },
      { id:'read_count',            label:'Read Count',              type:'number',   required:false },
      { id:'rarefaction_depth',     label:'Rarefaction Depth',       type:'number',   required:false },
      { id:'classifier',            label:'Classifier DB',           type:'text',     required:false },
      { id:'min_freq_threshold',    label:'Min Frequency Threshold', type:'number',   required:false },
    ],
  },
  {
    id: 'builtin-microscopy',
    name: 'Microscopy Session',
    description: 'Light and electron microscopy records',
    isBuiltIn: true,
    forFormats: ['tif','tiff','png','jpg','cif'],
    fields: [
      { id:'microscope_type',       label:'Microscope Type',         type:'select',   required:false, options:['Light/Brightfield','Fluorescence','Confocal','SEM','TEM','Transmission','Phase contrast','DIC'] },
      { id:'magnification',         label:'Magnification',           type:'text',     required:false, placeholder:'e.g. 40x, 100x oil' },
      { id:'objective',             label:'Objective',               type:'text',     required:false },
      { id:'stain_protocol',        label:'Stain / Protocol',        type:'text',     required:false },
      { id:'fluorophore',           label:'Fluorophore',             type:'text',     required:false },
      { id:'excitation_nm',         label:'Excitation (nm)',         type:'number',   required:false },
      { id:'emission_nm',           label:'Emission (nm)',           type:'number',   required:false },
      { id:'image_remarks',         label:'Image Remarks',           type:'textarea', required:false },
    ],
  },
  {
    id: 'builtin-isa-tab',
    name: 'ISA-Tab Study Record',
    description: 'ISA-Tab compatible study / assay metadata',
    isBuiltIn: true,
    forFormats: ['txt','tab'],
    fields: [
      { id:'study_title',           label:'Study Title',             type:'text',     required:false },
      { id:'study_identifier',      label:'Study Identifier',        type:'text',     required:false },
      { id:'assay_technology_type', label:'Assay Technology Type',   type:'text',     required:false },
      { id:'measurement_type',      label:'Measurement Type',        type:'text',     required:false },
      { id:'technology_platform',   label:'Technology Platform',     type:'text',     required:false },
      { id:'protocol_ref',          label:'Protocol Reference',      type:'text',     required:false },
      { id:'factor_value',          label:'Factor Value',            type:'text',     required:false },
    ],
  },
  {
    id: 'builtin-atmospheric',
    name: 'Atmospheric Observation',
    description: 'Weather station and atmospheric sensor logs',
    isBuiltIn: true,
    forFormats: ['csv','txt','json'],
    fields: [
      { id:'station_id',            label:'Station ID',              type:'text',     required:false },
      { id:'temperature_c',         label:'Temperature (°C)',        type:'number',   required:false },
      { id:'relative_humidity',     label:'Relative Humidity (%)',   type:'number',   required:false },
      { id:'pressure_hpa',          label:'Pressure (hPa)',          type:'number',   required:false },
      { id:'wind_speed_ms',         label:'Wind Speed (m/s)',        type:'number',   required:false },
      { id:'wind_direction_deg',    label:'Wind Direction (°)',      type:'number',   required:false },
      { id:'precipitation_mm',      label:'Precipitation (mm)',      type:'number',   required:false },
      { id:'sensor_model',          label:'Sensor Model',            type:'text',     required:false },
    ],
  },
  {
    id: 'builtin-clinical-fhir',
    name: 'Clinical Sample (FHIR)',
    description: 'FHIR-adjacent patient sample records',
    isBuiltIn: true,
    forFormats: ['json','xml'],
    fields: [
      { id:'sample_id',             label:'Sample ID',               type:'text',     required:false },
      { id:'specimen_type',         label:'Specimen Type',           type:'text',     required:false },
      { id:'collection_date',       label:'Collection Date',         type:'date',     required:false },
      { id:'body_site',             label:'Body Site',               type:'text',     required:false },
      { id:'collection_method',     label:'Collection Method',       type:'text',     required:false },
      { id:'storage_conditions',    label:'Storage Conditions',      type:'text',     required:false },
      { id:'processing_method',     label:'Processing Method',       type:'text',     required:false },
      { id:'clinical_remarks',      label:'Clinical Remarks',        type:'textarea', required:false },
    ],
  },
  {
    id: 'builtin-custom-blank',
    name: 'Custom (Blank)',
    description: 'Start entirely from scratch — no pre-defined fields',
    isBuiltIn: true,
    forFormats: ['*'],
    fields: [],
  },
];
